### ISSUE TITLE
这个处理代码有问题哦，会出现负索引的触发词，而且训练集中有两句的触发词没在句子中。或者是我的数据集有问题

### ISSUE THREAD

**Issue by Nic-bit** [yujunhuics/ace2005_Chinese_Processing#1]

**Comment by waow123** [comment]
您好，我在在做中文的时间抽取请问有处理好的ACE2005中文数据集吗，这是我的邮箱（963962704@qq.com），如果有的话能给我发一份吗，万分感谢！

**Comment by waow123** [comment]
您好，我也在做中文的事件抽取，请问有处理好的ACE2005中文数据集吗，这是我的邮箱（963962704@qq.com），如果有的话能给我发一份吗，万分感谢！
